import { RouteData } from "./RouteTable";

// Active routes
export const activeRoutes: RouteData[] = [
  {
    id: "RT-1234",
    name: "Los Angeles to San Francisco",
    vehicle: "26ft Box Truck",
    driver: "Michael Brown",
    stops: 5,
    distance: 382.5,
    duration: 405, // 6h 45m
    startLocation: "Los Angeles Distribution Center",
    endLocation: "San Francisco Warehouse",
    status: "active",
    fuelConsumption: 42.3,
    co2Emissions: 431.5,
    startTime: "08:15 AM",
    completionRate: 65,
  },
  {
    id: "RT-2345",
    name: "San Diego to Las Vegas",
    vehicle: "53ft Semi-Truck",
    driver: "Sarah Johnson",
    stops: 3,
    distance: 327.8,
    duration: 330, // 5h 30m
    startLocation: "San Diego Depot",
    endLocation: "Las Vegas Distribution Center",
    status: "in_progress",
    fuelConsumption: 49.2,
    co2Emissions: 501.7,
    startTime: "07:30 AM",
    completionRate: 32,
  },
  {
    id: "RT-3456",
    name: "Sacramento to Reno",
    vehicle: "Electric Delivery Van",
    driver: "James Wilson",
    stops: 4,
    distance: 132.5,
    duration: 150, // 2h 30m
    startLocation: "Sacramento Warehouse",
    endLocation: "Reno Fulfillment Center",
    status: "delayed",
    fuelConsumption: 0,
    co2Emissions: 35.8,
    startTime: "09:45 AM",
    completionRate: 48,
  },
  {
    id: "RT-4567",
    name: "Seattle to Portland",
    vehicle: "26ft Box Truck",
    driver: "Lisa Chen",
    stops: 2,
    distance: 174.2,
    duration: 180, // 3h 0m
    startLocation: "Seattle Distribution Center",
    endLocation: "Portland Warehouse",
    status: "active",
    fuelConsumption: 19.5,
    co2Emissions: 198.7,
    startTime: "10:30 AM",
    completionRate: 80,
  },
  {
    id: "RT-5678",
    name: "Denver to Salt Lake City",
    vehicle: "53ft Semi-Truck",
    driver: "David Martinez",
    stops: 6,
    distance: 504.8,
    duration: 480, // 8h 0m
    startLocation: "Denver Logistics Hub",
    endLocation: "Salt Lake City Center",
    status: "active",
    fuelConsumption: 75.7,
    co2Emissions: 772.3,
    startTime: "05:45 AM",
    completionRate: 25,
  },
  {
    id: "RT-6789",
    name: "Phoenix to Tucson",
    vehicle: "Delivery Van",
    driver: "Alex Johnson",
    stops: 3,
    distance: 116.5,
    duration: 120, // 2h 0m
    startLocation: "Phoenix Distribution Center",
    endLocation: "Tucson Warehouse",
    status: "in_progress",
    fuelConsumption: 11.2,
    co2Emissions: 114.2,
    startTime: "11:15 AM",
    completionRate: 55,
  },
];

// Scheduled routes
export const scheduledRoutes: RouteData[] = [
  {
    id: "RT-7890",
    name: "San Jose to Fresno",
    vehicle: "26ft Box Truck",
    driver: "Michael Brown",
    stops: 4,
    distance: 152.3,
    duration: 165, // 2h 45m
    startLocation: "San Jose Warehouse",
    endLocation: "Fresno Distribution Center",
    departureDate: "2023-09-16",
    departureTime: "08:00 AM",
    status: "scheduled",
    fuelConsumption: 16.9,
    co2Emissions: 172.1,
  },
  {
    id: "RT-8901",
    name: "Oakland to Sacramento",
    vehicle: "Electric Delivery Van",
    driver: "Sarah Johnson",
    stops: 2,
    distance: 87.5,
    duration: 90, // 1h 30m
    startLocation: "Oakland Depot",
    endLocation: "Sacramento Warehouse",
    departureDate: "2023-09-16",
    departureTime: "09:30 AM",
    status: "optimized",
    fuelConsumption: 0,
    co2Emissions: 23.6,
  },
  {
    id: "RT-9012",
    name: "Los Angeles to San Diego",
    vehicle: "Delivery Van",
    driver: "James Wilson",
    stops: 5,
    distance: 120.8,
    duration: 135, // 2h 15m
    startLocation: "Los Angeles Distribution Center",
    endLocation: "San Diego Depot",
    departureDate: "2023-09-17",
    departureTime: "07:15 AM",
    status: "scheduled",
    fuelConsumption: 11.6,
    co2Emissions: 118.4,
  },
  {
    id: "RT-0123",
    name: "San Francisco to Monterey",
    vehicle: "26ft Box Truck",
    driver: "Lisa Chen",
    stops: 3,
    distance: 118.2,
    duration: 150, // 2h 30m
    startLocation: "San Francisco Warehouse",
    endLocation: "Monterey Distribution Center",
    departureDate: "2023-09-18",
    departureTime: "06:45 AM",
    status: "scheduled",
    fuelConsumption: 13.1,
    co2Emissions: 133.6,
  },
  {
    id: "RT-1234",
    name: "Portland to Seattle",
    vehicle: "53ft Semi-Truck",
    driver: "David Martinez",
    stops: 2,
    distance: 174.2,
    duration: 180, // 3h 0m
    startLocation: "Portland Warehouse",
    endLocation: "Seattle Distribution Center",
    departureDate: "2023-09-19",
    departureTime: "05:30 AM",
    status: "planned",
    fuelConsumption: 26.1,
    co2Emissions: 266.5,
  },
  {
    id: "RT-2345",
    name: "Las Vegas to Phoenix",
    vehicle: "Delivery Van",
    driver: "Alex Johnson",
    stops: 4,
    distance: 297.3,
    duration: 300, // 5h 0m
    startLocation: "Las Vegas Distribution Center",
    endLocation: "Phoenix Warehouse",
    departureDate: "2023-09-20",
    departureTime: "04:00 AM",
    status: "scheduled",
    fuelConsumption: 28.5,
    co2Emissions: 290.9,
  },
  {
    id: "RT-3456",
    name: "Salt Lake City to Denver",
    vehicle: "53ft Semi-Truck",
    driver: "Emily Clark",
    stops: 5,
    distance: 504.8,
    duration: 480, // 8h 0m
    startLocation: "Salt Lake City Center",
    endLocation: "Denver Logistics Hub",
    departureDate: "2023-09-21",
    departureTime: "03:30 AM",
    status: "scheduled",
    fuelConsumption: 75.7,
    co2Emissions: 772.3,
  },
];

// Completed routes
export const completedRoutes: RouteData[] = [
  {
    id: "RT-4567",
    name: "Los Angeles to San Francisco",
    vehicle: "26ft Box Truck",
    driver: "Michael Brown",
    stops: 5,
    distance: 382.5,
    duration: 405, // 6h 45m
    actualDuration: 423, // 7h 3m
    startLocation: "Los Angeles Distribution Center",
    endLocation: "San Francisco Warehouse",
    departureDate: "2023-09-10",
    departureTime: "08:00 AM",
    status: "completed",
    fuelConsumption: 42.3,
    co2Emissions: 431.5,
    startTime: "08:15 AM",
    endTime: "03:18 PM",
    completionRate: 100,
  },
  {
    id: "RT-5678",
    name: "San Diego to Las Vegas",
    vehicle: "53ft Semi-Truck",
    driver: "Sarah Johnson",
    stops: 3,
    distance: 327.8,
    duration: 330, // 5h 30m
    actualDuration: 315, // 5h 15m
    startLocation: "San Diego Depot",
    endLocation: "Las Vegas Distribution Center",
    departureDate: "2023-09-11",
    departureTime: "07:30 AM",
    status: "completed",
    fuelConsumption: 49.2,
    co2Emissions: 501.7,
    startTime: "07:45 AM",
    endTime: "01:00 PM",
    completionRate: 100,
  },
  {
    id: "RT-6789",
    name: "Sacramento to Reno",
    vehicle: "Electric Delivery Van",
    driver: "James Wilson",
    stops: 4,
    distance: 132.5,
    duration: 150, // 2h 30m
    actualDuration: 180, // 3h 0m
    startLocation: "Sacramento Warehouse",
    endLocation: "Reno Fulfillment Center",
    departureDate: "2023-09-12",
    departureTime: "09:45 AM",
    status: "completed",
    fuelConsumption: 0,
    co2Emissions: 35.8,
    startTime: "10:00 AM",
    endTime: "01:00 PM",
    completionRate: 100,
  },
  {
    id: "RT-7890",
    name: "Seattle to Portland",
    vehicle: "26ft Box Truck",
    driver: "Lisa Chen",
    stops: 2,
    distance: 174.2,
    duration: 180, // 3h 0m
    actualDuration: 165, // 2h 45m
    startLocation: "Seattle Distribution Center",
    endLocation: "Portland Warehouse",
    departureDate: "2023-09-13",
    departureTime: "10:30 AM",
    status: "completed",
    fuelConsumption: 19.5,
    co2Emissions: 198.7,
    startTime: "10:45 AM",
    endTime: "01:30 PM",
    completionRate: 100,
  },
  {
    id: "RT-8901",
    name: "Denver to Salt Lake City",
    vehicle: "53ft Semi-Truck",
    driver: "David Martinez",
    stops: 6,
    distance: 504.8,
    duration: 480, // 8h 0m
    actualDuration: 510, // 8h 30m
    startLocation: "Denver Logistics Hub",
    endLocation: "Salt Lake City Center",
    departureDate: "2023-09-14",
    departureTime: "05:45 AM",
    status: "completed",
    fuelConsumption: 75.7,
    co2Emissions: 772.3,
    startTime: "06:00 AM",
    endTime: "02:30 PM",
    completionRate: 100,
  },
];

// Route templates
export const routeTemplates: RouteData[] = [
  {
    id: "TPL-1234",
    name: "LA to SF Standard Route",
    vehicle: "26ft Box Truck",
    driver: "Unassigned",
    stops: 5,
    distance: 382.5,
    duration: 405, // 6h 45m
    startLocation: "Los Angeles Distribution Center",
    endLocation: "San Francisco Warehouse",
    status: "template",
    fuelConsumption: 42.3,
    co2Emissions: 431.5,
  },
  {
    id: "TPL-2345",
    name: "SD to LV Express",
    vehicle: "53ft Semi-Truck",
    driver: "Unassigned",
    stops: 3,
    distance: 327.8,
    duration: 330, // 5h 30m
    startLocation: "San Diego Depot",
    endLocation: "Las Vegas Distribution Center",
    status: "template",
    fuelConsumption: 49.2,
    co2Emissions: 501.7,
  },
  {
    id: "TPL-3456",
    name: "Sacramento-Reno Green Route",
    vehicle: "Electric Delivery Van",
    driver: "Unassigned",
    stops: 4,
    distance: 132.5,
    duration: 150, // 2h 30m
    startLocation: "Sacramento Warehouse",
    endLocation: "Reno Fulfillment Center",
    status: "template",
    fuelConsumption: 0,
    co2Emissions: 35.8,
  },
  {
    id: "TPL-4567",
    name: "Seattle-Portland Direct",
    vehicle: "26ft Box Truck",
    driver: "Unassigned",
    stops: 2,
    distance: 174.2,
    duration: 180, // 3h 0m
    startLocation: "Seattle Distribution Center",
    endLocation: "Portland Warehouse",
    status: "template",
    fuelConsumption: 19.5,
    co2Emissions: 198.7,
  },
]; 