import { RouteData } from "./RouteTable";

// Mock active routes
export const activeRoutes: RouteData[] = [
  {
    id: "RT-1234",
    name: "Downtown Delivery Route",
    vehicle: "26ft Box Truck #102",
    driver: "Michael Johnson", 
    stops: 12,
    distance: 28.5,
    duration: 180,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "active",
    routeType: "delivery",
    startTime: "08:45 AM",
    completionRate: 45,
    fuelConsumption: 4.8,
    co2Emissions: 42.3
  },
  {
    id: "RT-1235",
    name: "North Side Delivery",
    vehicle: "Delivery Van #208",
    driver: "Sarah Wilson",
    stops: 8,
    distance: 18.2,
    duration: 120,
    startLocation: "North Distribution Center",
    endLocation: "North Distribution Center",
    status: "active",
    routeType: "delivery",
    startTime: "09:15 AM",
    completionRate: 75,
    fuelConsumption: 2.4,
    co2Emissions: 21.6
  },
  {
    id: "RT-1237",
    name: "Supplier Pickup Route",
    vehicle: "Semi-Truck #004",
    driver: "Robert Clark",
    stops: 4,
    distance: 52.6,
    duration: 240,
    startLocation: "Main Warehouse",
    endLocation: "Regional Warehouse",
    status: "active",
    routeType: "pickup",
    startTime: "07:30 AM",
    completionRate: 25,
    fuelConsumption: 12.8,
    co2Emissions: 118.2
  },
  {
    id: "RT-1238",
    name: "South Express Delivery",
    vehicle: "Delivery Van #215", 
    driver: "Jennifer Adams",
    stops: 14,
    distance: 22.4,
    duration: 150,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "active",
    routeType: "delivery",
    startTime: "10:00 AM",
    completionRate: 35,
    fuelConsumption: 3.1,
    co2Emissions: 27.5
  },
  {
    id: "RT-1239",
    name: "Inventory Transfer Route",
    vehicle: "26ft Box Truck #105",
    driver: "David Martinez",
    stops: 2,
    distance: 65.1,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Secondary Warehouse",
    status: "in_progress",
    routeType: "transfer",
    startTime: "08:15 AM",
    completionRate: 50,
    fuelConsumption: 8.4,
    co2Emissions: 76.8
  },
  {
    id: "RT-1241",
    name: "Downtown Express Delivery",
    vehicle: "Electric Van #301",
    driver: "Emily Rodriguez",
    stops: 16,
    distance: 24.8,
    duration: 165,
    startLocation: "East Distribution Center",
    endLocation: "East Distribution Center",
    status: "active",
    routeType: "delivery",
    startTime: "08:30 AM",
    completionRate: 62,
    fuelConsumption: 0,
    co2Emissions: 0
  },
  {
    id: "RT-1244",
    name: "Parts Return Route",
    vehicle: "Delivery Van #210",
    driver: "Kevin Thompson",
    stops: 5,
    distance: 42.7,
    duration: 195,
    startLocation: "Main Warehouse",
    endLocation: "Supplier Facility",
    status: "active",
    routeType: "return",
    startTime: "09:45 AM",
    completionRate: 30,
    fuelConsumption: 5.6,
    co2Emissions: 51.2
  },
  {
    id: "RT-1250",
    name: "West Zone Distribution",
    vehicle: "26ft Box Truck #107",
    driver: "Brian Wilson",
    stops: 9,
    distance: 33.5,
    duration: 185,
    startLocation: "West Distribution Center",
    endLocation: "West Distribution Center",
    status: "active",
    routeType: "delivery",
    startTime: "07:45 AM",
    completionRate: 80,
    fuelConsumption: 4.9,
    co2Emissions: 45.7
  }
];

// Mock scheduled routes
export const scheduledRoutes: RouteData[] = [
  {
    id: "RT-1240",
    name: "East Zone Delivery",
    vehicle: "Delivery Van #202",
    driver: "Christopher Lee",
    stops: 10,
    distance: 24.3,
    duration: 165,
    startLocation: "East Distribution Center",
    endLocation: "East Distribution Center",
    departureTime: "08:00 AM",
    departureDate: "2023-06-15",
    status: "scheduled",
    routeType: "delivery",
    fuelConsumption: 3.6,
    co2Emissions: 32.5
  },
  {
    id: "RT-1242",
    name: "West Side Delivery Route", 
    vehicle: "Delivery Van #210",
    driver: "Amanda White",
    stops: 16,
    distance: 32.1,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    departureTime: "09:30 AM",
    departureDate: "2023-06-15",
    status: "scheduled",
    routeType: "delivery",
    fuelConsumption: 4.8,
    co2Emissions: 43.2
  },
  {
    id: "RT-1243",
    name: "Parts Return Route",
    vehicle: "Box Truck #103",
    driver: "Thomas Brown",
    stops: 6,
    distance: 48.2,
    duration: 240,
    startLocation: "Main Warehouse",
    endLocation: "Supplier Facility",
    departureTime: "10:15 AM",
    departureDate: "2023-06-15",
    status: "scheduled",
    routeType: "return",
    fuelConsumption: 7.6,
    co2Emissions: 68.4
  },
  {
    id: "RT-1245",
    name: "Downtown Express Delivery",
    vehicle: "Delivery Van #204",
    driver: "Jessica Miller",
    stops: 18,
    distance: 28.6,
    duration: 195,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    departureTime: "08:45 AM",
    departureDate: "2023-06-16",
    status: "optimized",
    routeType: "delivery",
    fuelConsumption: 4.2,
    co2Emissions: 38.1
  },
  {
    id: "RT-1246",
    name: "Rural Zone Delivery",
    vehicle: "Delivery Van #211",
    driver: "Daniel Johnson",
    stops: 7,
    distance: 68.3,
    duration: 260,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    departureTime: "08:00 AM",
    departureDate: "2023-06-16",
    status: "scheduled",
    routeType: "delivery",
    fuelConsumption: 9.8,
    co2Emissions: 88.2
  },
  {
    id: "RT-1248",
    name: "Regional Transfer Route",
    vehicle: "Semi-Truck #006",
    driver: "Ryan Wilson",
    stops: 3,
    distance: 124.6,
    duration: 345,
    startLocation: "Main Warehouse",
    endLocation: "Regional Distribution Center",
    departureTime: "06:30 AM",
    departureDate: "2023-06-16",
    status: "scheduled",
    routeType: "transfer",
    fuelConsumption: 28.4,
    co2Emissions: 255.6
  },
  {
    id: "RT-1249",
    name: "Supplier Pickup Route",
    vehicle: "Box Truck #108",
    driver: "Matthew Thompson",
    stops: 5,
    distance: 42.5,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    departureTime: "07:45 AM",
    departureDate: "2023-06-17",
    status: "scheduled",
    routeType: "pickup",
    fuelConsumption: 6.8,
    co2Emissions: 61.2
  },
  {
    id: "RT-1251",
    name: "Urban Express Route",
    vehicle: "Electric Van #302",
    driver: "Sophia Garcia",
    stops: 15,
    distance: 26.2,
    duration: 180,
    startLocation: "Downtown Hub",
    endLocation: "Downtown Hub",
    departureTime: "10:00 AM",
    departureDate: "2023-06-17",
    status: "optimized",
    routeType: "delivery",
    fuelConsumption: 0,
    co2Emissions: 0
  },
  {
    id: "RT-1252",
    name: "North County Delivery",
    vehicle: "Delivery Van #213",
    driver: "Alex Rodriguez",
    stops: 12,
    distance: 45.3,
    duration: 225,
    startLocation: "North Distribution Center",
    endLocation: "North Distribution Center",
    departureTime: "09:15 AM",
    departureDate: "2023-06-18",
    status: "scheduled",
    routeType: "delivery",
    fuelConsumption: 6.5,
    co2Emissions: 58.8
  },
  {
    id: "RT-1253",
    name: "Hardware Returns Route",
    vehicle: "Box Truck #106",
    driver: "Olivia Chen",
    stops: 8,
    distance: 37.6,
    duration: 195,
    startLocation: "Main Warehouse",
    endLocation: "Hardware Supplier",
    departureTime: "08:30 AM",
    departureDate: "2023-06-19",
    status: "scheduled",
    routeType: "return",
    fuelConsumption: 5.9,
    co2Emissions: 53.2
  }
];

// Mock completed routes
export const completedRoutes: RouteData[] = [
  {
    id: "RT-1123",
    name: "Downtown Delivery Route",
    vehicle: "Delivery Van #201",
    driver: "Michael Johnson",
    stops: 14,
    distance: 32.5,
    duration: 195,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "completed",
    routeType: "delivery",
    startTime: "08:00 AM",
    endTime: "11:42 AM",
    actualDuration: 222,
    completionRate: 100,
    fuelConsumption: 4.9,
    co2Emissions: 44.1
  },
  {
    id: "RT-1124",
    name: "North Side Delivery Route",
    vehicle: "Delivery Van #205",
    driver: "Sarah Wilson",
    stops: 10,
    distance: 18.6,
    duration: 135,
    startLocation: "North Distribution Center",
    endLocation: "North Distribution Center",
    status: "completed",
    routeType: "delivery",
    startTime: "09:00 AM",
    endTime: "11:10 AM",
    actualDuration: 130,
    completionRate: 100,
    fuelConsumption: 2.6,
    co2Emissions: 23.4
  },
  {
    id: "RT-1125",
    name: "Supplier Pickup Route",
    vehicle: "Box Truck #104",
    driver: "Robert Clark",
    stops: 4,
    distance: 48.2,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "completed",
    routeType: "pickup",
    startTime: "07:30 AM",
    endTime: "11:15 AM",
    actualDuration: 225,
    completionRate: 100,
    fuelConsumption: 7.6,
    co2Emissions: 68.4
  },
  {
    id: "RT-1126",
    name: "East Zone Delivery",
    vehicle: "Delivery Van #207",
    driver: "Jennifer Adams",
    stops: 12,
    distance: 24.8,
    duration: 165,
    startLocation: "East Distribution Center",
    endLocation: "East Distribution Center",
    status: "completed",
    routeType: "delivery",
    startTime: "08:15 AM",
    endTime: "10:50 AM",
    actualDuration: 155,
    completionRate: 100,
    fuelConsumption: 3.4,
    co2Emissions: 30.6
  },
  {
    id: "RT-1127",
    name: "West Side Express Delivery",
    vehicle: "Delivery Van #203",
    driver: "David Martinez",
    stops: 16,
    distance: 28.5,
    duration: 180,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "completed",
    routeType: "delivery",
    startTime: "09:30 AM",
    endTime: "12:45 PM",
    actualDuration: 195,
    completionRate: 100,
    fuelConsumption: 4.2,
    co2Emissions: 37.8
  },
  {
    id: "RT-1128",
    name: "Regional Transfer Route",
    vehicle: "Semi-Truck #002",
    driver: "Christopher Lee",
    stops: 2,
    distance: 112.4,
    duration: 300,
    startLocation: "Main Warehouse",
    endLocation: "Regional Distribution Center",
    status: "completed",
    routeType: "transfer",
    startTime: "06:00 AM",
    endTime: "10:45 AM",
    actualDuration: 285,
    completionRate: 100,
    fuelConsumption: 26.8,
    co2Emissions: 241.2
  },
  {
    id: "RT-1130",
    name: "Overnight Express Delivery",
    vehicle: "Delivery Van #212",
    driver: "Emma Scott",
    stops: 9,
    distance: 19.8,
    duration: 120,
    startLocation: "Downtown Hub",
    endLocation: "Downtown Hub",
    status: "completed",
    routeType: "delivery",
    startTime: "11:00 PM",
    endTime: "01:35 AM",
    actualDuration: 115,
    completionRate: 100,
    fuelConsumption: 2.8,
    co2Emissions: 25.2
  },
  {
    id: "RT-1131",
    name: "Rural Delivery Route",
    vehicle: "Box Truck #107",
    driver: "James Peterson",
    stops: 6,
    distance: 72.4,
    duration: 240,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "completed",
    routeType: "delivery",
    startTime: "07:30 AM",
    endTime: "11:40 AM",
    actualDuration: 250,
    completionRate: 100,
    fuelConsumption: 10.8,
    co2Emissions: 97.2
  },
  {
    id: "RT-1132",
    name: "Green Delivery Route",
    vehicle: "Electric Van #301",
    driver: "Natalie Chen",
    stops: 14,
    distance: 25.6,
    duration: 180,
    startLocation: "Downtown Hub",
    endLocation: "Downtown Hub",
    status: "completed",
    routeType: "delivery",
    startTime: "09:00 AM",
    endTime: "12:15 PM",
    actualDuration: 195,
    completionRate: 100,
    fuelConsumption: 0,
    co2Emissions: 0
  },
  {
    id: "RT-1133",
    name: "Return Merchandise Route",
    vehicle: "Box Truck #105",
    driver: "Lucas Brown",
    stops: 7,
    distance: 45.2,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Returns Center",
    status: "completed",
    routeType: "return",
    startTime: "08:45 AM",
    endTime: "12:10 PM",
    actualDuration: 205,
    completionRate: 100,
    fuelConsumption: 6.8,
    co2Emissions: 61.2
  }
];

// Mock route templates
export const routeTemplates: RouteData[] = [
  {
    id: "TPL-001",
    name: "Standard Downtown Delivery",
    vehicle: "",
    driver: "",
    stops: 12,
    distance: 28.6,
    duration: 180,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 4.3,
    co2Emissions: 38.7
  },
  {
    id: "TPL-002",
    name: "North Side Delivery Template",
    vehicle: "",
    driver: "",
    stops: 8,
    distance: 18.4,
    duration: 120,
    startLocation: "North Distribution Center",
    endLocation: "North Distribution Center",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 2.5,
    co2Emissions: 22.5
  },
  {
    id: "TPL-003",
    name: "Weekly Supplier Pickup",
    vehicle: "",
    driver: "",
    stops: 4,
    distance: 52.8,
    duration: 240,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "template",
    routeType: "pickup",
    fuelConsumption: 8.4,
    co2Emissions: 75.6
  },
  {
    id: "TPL-004",
    name: "East Zone Delivery Template",
    vehicle: "",
    driver: "",
    stops: 10,
    distance: 22.6,
    duration: 150,
    startLocation: "East Distribution Center",
    endLocation: "East Distribution Center",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 3.2,
    co2Emissions: 28.8
  },
  {
    id: "TPL-005",
    name: "Warehouse Transfer Template",
    vehicle: "",
    driver: "",
    stops: 2,
    distance: 65.8,
    duration: 210,
    startLocation: "Main Warehouse",
    endLocation: "Secondary Warehouse",
    status: "template",
    routeType: "transfer",
    fuelConsumption: 9.8,
    co2Emissions: 88.2
  },
  {
    id: "TPL-006",
    name: "Rural Zone Delivery Template",
    vehicle: "",
    driver: "",
    stops: 6,
    distance: 72.4,
    duration: 270,
    startLocation: "Main Warehouse",
    endLocation: "Main Warehouse",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 10.2,
    co2Emissions: 91.8
  },
  {
    id: "TPL-007",
    name: "Urban Express Delivery Template",
    vehicle: "",
    driver: "",
    stops: 15,
    distance: 26.8,
    duration: 195,
    startLocation: "Downtown Hub",
    endLocation: "Downtown Hub",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 3.9,
    co2Emissions: 35.1
  },
  {
    id: "TPL-008",
    name: "Electronics Supplier Pickup",
    vehicle: "",
    driver: "",
    stops: 3,
    distance: 32.5,
    duration: 180,
    startLocation: "Main Warehouse",
    endLocation: "Electronics Supplier",
    status: "template",
    routeType: "pickup",
    fuelConsumption: 4.8,
    co2Emissions: 43.2
  },
  {
    id: "TPL-009",
    name: "Green Downtown Delivery",
    vehicle: "",
    driver: "",
    stops: 14,
    distance: 25.7,
    duration: 165,
    startLocation: "Downtown Hub",
    endLocation: "Downtown Hub",
    status: "template",
    routeType: "delivery",
    fuelConsumption: 0,
    co2Emissions: 0
  },
  {
    id: "TPL-010",
    name: "Monthly Returns Template",
    vehicle: "",
    driver: "",
    stops: 7,
    distance: 45.2,
    duration: 240,
    startLocation: "Main Warehouse",
    endLocation: "Returns Center",
    status: "template",
    routeType: "return",
    fuelConsumption: 6.8,
    co2Emissions: 61.2
  }
]; 